export const BASE = {
  AA: "4,5,8",
  AD: "1",
  AE: "1",
  AF: "1",
  AG: "1",
  AH: "1",
  AK: "1",
  AL: "1",
  AM: "1",
  AN: "1",
  BA: "1",
  BB: "1",
  BC: "1",
  BD: "1",
  BE: "1",
  CA: "1",
  CB: "1",
} as const;

/** Valeurs par défaut si aucun preset local (même format que BASE). */
export const DEFAULT_FACTORS = { ...BASE };

export const LOCALS = {
  bureau: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  open_space: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  salle_reunion: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  couloir: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  sanitaires: {
    AA: "4,5,8",
    AD: "2",
    AE: "2",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  cuisine: {
    AA: "4,5,8",
    AD: "2",
    AE: "2",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  cuisine_pro: {
    AA: "4,5,8",
    AD: "2",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  chaufferie: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "2",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  local_technique: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  atelier: {
    AA: "4,5,8",
    AD: "1",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  laboratoire: {
    AA: "4,5,8",
    AD: "1",
    AE: "2",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  magasin: {
    AA: "4,5,8",
    AD: "1",
    AE: "1",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "1",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  restaurant: {
    AA: "4,5,8",
    AD: "2",
    AE: "2",
    AF: "1",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  parking: {
    AA: "7,8",
    AD: "2",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "2",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  garage: {
    AA: "7,8",
    AD: "2",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "2",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  garage_collectif: {
    AA: "7,8",
    AD: "2",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "2",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  lavage_voiture: {
    AA: "7,8",
    AD: "2",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "2",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  hall_logistique: {
    AA: "4,5,8",
    AD: "1",
    AE: "2",
    AF: "2",
    AG: "1",
    AH: "1",
    AK: "1",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "1",
    BB: "1",
    BC: "1",
    BD: "2",
    BE: "1",
    CA: "1",
    CB: "1",
  },

  hopital: {
    BA: "2,3",
    BD: "3,4",
  },

  /** Preset aligné fiche « Cabine haute tension » (BC 2, AM 2, BA 5, etc.) */
  cabine_haute_tension: {
    AM: "2",
    BA: "5",
    BC: "2",
  },

  exterieur: {
    AA: "7,8",
    AN: "2",
  },

  /** WC — BC 1 (classe normale), AD renforcé */
  wc: {
    AD: "2",
  },

  /** Kitchenette — BE 2 zones humides, BC 1 */
  kitchenette: {
    AD: "2",
    BE: "2",
  },

  /** Scierie — BC 2 */
  scierie: {
    AE: "4",
    AF: "1",
    AG: "2",
    AH: "2",
    AK: "2",
    AL: "1",
    AM: "1",
    AN: "1",
    BA: "4",
    BB: "1",
    BC: "2",
    BD: "1",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  /** Atelier soudure — BC 2 */
  atelier_soudure: {
    AF: "3",
    AG: "2",
    AH: "2",
    AK: "1",
    AL: "1",
    AM: "3",
    AN: "1",
    BA: "4",
    BB: "1",
    BC: "2",
    BD: "1",
    BE: "2",
    CA: "1",
    CB: "1",
  },

  grenier: {},

  cave: {},

  buanderie: {
    AD: "2",
    BE: "2",
  },

  sechoir: {},
} as const;

export type LocalKey = keyof typeof LOCALS;

export function generateFactors(localKey: LocalKey) {
  return {
    ...BASE,
    ...(LOCALS[localKey] || {}),
  };
}

function normalizeLabelForLookup(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ");
}

/**
 * Libellé écran (après `normalizeLabelForLookup`) → clé `LOCALS`.
 * Anciennes entrées conservées pour compatibilité exports / données existantes.
 */
export const LABEL_TO_LOCAL_KEY: Partial<Record<string, LocalKey>> = {
  // ——— Presets AREI (libellés ↔ LOCALS) ———
  bureau: "bureau",
  "open space": "open_space",
  sanitaires: "sanitaires",
  "salle reunion": "salle_reunion",
  couloir: "couloir",
  cuisine: "cuisine",
  "cuisine pro": "cuisine_pro",
  chaufferie: "chaufferie",
  "local technique": "local_technique",
  atelier: "atelier",
  laboratoire: "laboratoire",
  magasin: "magasin",
  restaurant: "restaurant",
  parking: "parking",
  garage: "garage",
  "garage collectif": "garage_collectif",
  "lavage voiture": "lavage_voiture",
  "hall logistique": "hall_logistique",

  // ——— Historique / compat ———
  scierie: "scierie",
  grenier: "grenier",
  cave: "cave",
  buanderie: "buanderie",
  sechoir: "sechoir",

  // ——— Tertiaire / ERP ———
  "salle de reunion": "salle_reunion",
  "salle de conference": "salle_reunion",
  "salle de formation": "salle_reunion",
  "salle polyvalente": "salle_reunion",
  "salle d'attente": "salle_reunion",
  accueil: "magasin",
  reception: "magasin",
  hall: "magasin",
  cafeteria: "restaurant",
  cantine: "restaurant",
  creche: "hopital",
  vestiaires: "sanitaires",

  // ——— Commercial ———
  boutique: "magasin",
  showroom: "magasin",
  "cuisine professionnelle": "cuisine_pro",
  "zone de vente": "magasin",
  "zone client": "magasin",

  // ——— Technique (locaux techniques → preset `local_technique` sauf spécifique) ———
  "local electrique": "local_technique",
  tgbt: "local_technique",
  "tableau divisionnaire": "local_technique",
  "cabine ht": "cabine_haute_tension",
  "cabine haute tension": "cabine_haute_tension",
  "poste de livraison": "local_technique",
  "local transformateur": "local_technique",
  "local onduleur": "local_technique",
  "local batterie": "local_technique",
  "local ups": "local_technique",
  "local serveur": "local_technique",
  "data center": "local_technique",
  "local fibre": "local_technique",
  "local vdi": "local_technique",
  "local gtb": "local_technique",
  "local incendie": "local_technique",
  "local cta": "local_technique",
  "local pompe": "local_technique",
  "local pompe a chaleur": "local_technique",
  "local groupe electrogene": "local_technique",

  // ——— Industriel ———
  "atelier soudure": "atelier_soudure",
  "zone de production": "atelier",
  "zone de stockage": "atelier",
  "quai de chargement": "atelier",
  "local machine": "atelier",
  "local compresseur": "atelier",
  "local peinture": "atelier",
  "local soudure": "atelier_soudure",
  "local froid": "atelier",
  "local chaud": "atelier",
  "zone atex": "atelier",
  "zone humide": "cuisine_pro",
  "zone poussiereuse": "atelier",
  "zone corrosive": "laboratoire",
  "zone haute temperature": "atelier",
  "zone basse temperature": "atelier",

  // ——— Extérieur / infra ———
  "parking couvert": "parking",
  "aire de stationnement": "parking",
  "aire de livraison": "parking",
  "voie camion": "parking",
  exterieur: "exterieur",
  terrasse: "exterieur",
  cour: "exterieur",
  "toiture technique": "exterieur",
  facade: "exterieur",
  "sous-station": "exterieur",
  "abri velo": "exterieur",

  // ——— Transversal ———
  hopital: "hopital",
  wc: "wc",
  kitchenette: "kitchenette",
};

/** Facteurs AA→CB pour un libellé de local (DEFAULT_FACTORS si type inconnu). */
export function getFactorsForLocalLabel(label: string) {
  const norm = normalizeLabelForLookup(label);
  const key = LABEL_TO_LOCAL_KEY[norm];
  const fromPreset =
    key && key in LOCALS ? generateFactors(key) : { ...DEFAULT_FACTORS };
  return { ...DEFAULT_FACTORS, ...fromPreset };
}

export type FactorsRow = ReturnType<typeof generateFactors> & {
  local: string;
  public: boolean;
};
