/**
 * Locaux non domestiques (tertiaire, commercial, technique, industriel, extérieur).
 * Libellés d’affichage avec majuscule ; le mapping facteurs utilise des clés normalisées.
 */
export const LOCAL_CATEGORIES = [
  {
    title: "Tertiaire — Bureaux / ERP",
    items: [
      "Bureau",
      "Open space",
      "Salle de réunion",
      "Salle de conférence",
      "Salle de formation",
      "Accueil",
      "Réception",
      "Salle d'attente",
      "Hall",
      "Hall logistique",
      "Couloir",
      "Sanitaires",
      "WC",
      "Vestiaires",
      "Cafétéria",
      "Cantine",
      "Cuisine",
      "Kitchenette",
      "Crèche",
      "Salle polyvalente",
    ],
  },
  {
    title: "Commercial",
    items: [
      "Magasin",
      "Boutique",
      "Showroom",
      "Restaurant",
      "Cuisine professionnelle",
      "Zone de vente",
      "Zone client",
    ],
  },
  {
    title: "Technique",
    items: [
      "Local technique",
      "Local électrique",
      "TGBT",
      "Tableau divisionnaire",
      "Cabine HT",
      "Cabine haute tension",
      "Poste de livraison",
      "Local transformateur",
      "Local onduleur",
      "Local batterie",
      "Local UPS",
      "Local serveur",
      "Data center",
      "Local fibre",
      "Local VDI",
      "Local GTB",
      "Local incendie",
      "Chaufferie",
      "Local CTA",
      "Local pompe",
      "Local pompe à chaleur",
      "Local groupe électrogène",
    ],
  },
  {
    title: "Industriel",
    items: [
      "Atelier",
      "Atelier soudure",
      "Laboratoire",
      "Zone de production",
      "Zone de stockage",
      "Quai de chargement",
      "Local machine",
      "Local compresseur",
      "Local peinture",
      "Local soudure",
      "Local froid",
      "Local chaud",
      "Zone ATEX",
      "Zone humide",
      "Zone poussiéreuse",
      "Zone corrosive",
      "Zone haute température",
      "Zone basse température",
    ],
  },
  {
    title: "Extérieur / infrastructure",
    items: [
      "Parking",
      "Parking couvert",
      "Garage",
      "Garage collectif",
      "Aire de stationnement",
      "Aire de livraison",
      "Voie camion",
      "Lavage voiture",
      "Extérieur",
      "Terrasse",
      "Cour",
      "Toiture technique",
      "Façade",
      "Sous-station",
      "Abri vélo",
    ],
  },
];
